### PR TITLE
added: tests for upscaling relative permeability

### PR DESCRIPTION
**Pull request by akva2**
tests are due to lkerrand

### CODE REVIEW

**Comment by akva2** [comment]
@atgeirr please sanity check and hit the green.

**Comment by bska** [comment]
I don't know if I'm doing something wrong, but the get the following messages even from a clean build directory
```
make[2]: *** No rule to make target `/home/bska/work/opm/src/opm/opm-upscaling/tests/input_data/grids/stone1.txt', needed by `tests/input_data/grids/stone1.txt'.
make[2]: *** No rule to make target `/home/bska/work/opm/src/opm/opm-upscaling/tests/input_data/grids/stone2.txt', needed by `tests/input_data/grids/stone2.txt'.
make[2]: *** No rule to make target `/home/bska/work/opm/src/opm/opm-upscaling/tests/input_data/grids/stoneAniso.txt', needed by `tests/input_data/grids/stoneAniso.txt'.
make[2]: Target `CMakeFiles/datafiles.dir/build' not remade because of errors.
make[1]: *** [CMakeFiles/datafiles.dir/all] Error 2
```
This is just during `make`.  I have not gotten to `make test` yet.

**Comment by akva2** [comment]
nope, that's me. try now.

**Comment by bska** [comment]
>  try now

Much better, thank you.  We're still not quite golden, however

```
(cd dbg/seq/dune-2.3.1/opm-upscaling/ && make test)
Running tests...
Test project /data/projects/opm/build/opm/dbg/seq/dune-2.3.1/opm-upscaling
      Start  1: upscale_perm_BCp_PeriodicTilted
 1/14 Test  #1: upscale_perm_BCp_PeriodicTilted ....................................................................   Passed    7.48 sec
      Start  2: upscale_perm_BCflp_27cellsAniso
 2/14 Test  #2: upscale_perm_BCflp_27cellsAniso ....................................................................   Passed    0.30 sec
      Start  3: upscale_perm_BCflp_27cellsIso
 3/14 Test  #3: upscale_perm_BCflp_27cellsIso ......................................................................   Passed    0.11 sec
      Start  4: upscale_perm_BCfl_EightCells
 4/14 Test  #4: upscale_perm_BCfl_EightCells .......................................................................   Passed    0.09 sec
      Start  5: upscale_perm_BCflp_Hummocky
 5/14 Test  #5: upscale_perm_BCflp_Hummocky ........................................................................   Passed   29.47 sec
      Start  6: upscale_relperm_BCf_pts20_surfTens11_stonefile_benchmark_stonefile_benchmark_benchmark_tiny_grid
 6/14 Test  #6: upscale_relperm_BCf_pts20_surfTens11_stonefile_benchmark_stonefile_benchmark_benchmark_tiny_grid ...   Passed  123.35 sec
      Start  7: upscale_relperm_BCf_pts30_surfTens11_stone1_stone1_EightCells
 7/14 Test  #7: upscale_relperm_BCf_pts30_surfTens11_stone1_stone1_EightCells ......................................   Passed    1.22 sec
      Start  8: upscale_relperm_BCf_pts20_surfTens11_stone1_stone1_EightCells
 8/14 Test  #8: upscale_relperm_BCf_pts20_surfTens11_stone1_stone1_EightCells ......................................   Passed    1.14 sec
      Start  9: upscale_relperm_BCl_pts30_surfTens11_stone1_stone1_EightCells
 9/14 Test  #9: upscale_relperm_BCl_pts30_surfTens11_stone1_stone1_EightCells ......................................   Passed    1.19 sec
      Start 10: upscale_relperm_BCf_pts30_surfTens45_stone1_stone1_EightCells
10/14 Test #10: upscale_relperm_BCf_pts30_surfTens45_stone1_stone1_EightCells ......................................   Passed    1.20 sec
      Start 11: upscale_relperm_BCf_pts30_surfTens11_stone1_stone2_EightCells
11/14 Test #11: upscale_relperm_BCf_pts30_surfTens11_stone1_stone2_EightCells ......................................   Passed    1.12 sec
      Start 12: upscale_relperm_BCf_pts30_surfTens11_stoneAniso_stoneAniso_27cellsAniso
12/14 Test #12: upscale_relperm_BCf_pts30_surfTens11_stoneAniso_stoneAniso_27cellsAniso ............................   Passed    2.28 sec
      Start 13: upscale_elasticity_mpc_EightCells
13/14 Test #13: upscale_elasticity_mpc_EightCells ..................................................................***Failed    0.15 sec
      Start 14: upscale_elasticity_mortar_EightCells
14/14 Test #14: upscale_elasticity_mortar_EightCells ...............................................................***Failed    0.08 sec

86% tests passed, 2 tests failed out of 14

Total Test time (real) = 169.29 sec

The following tests FAILED:
	 13 - upscale_elasticity_mpc_EightCells (Failed)
	 14 - upscale_elasticity_mortar_EightCells (Failed)
Errors while running CTest
make: *** [test] Error 8
```

Note: This is a debug build with checked iterators so run-times are naturally poor.  I'm waiting for a release build to complete.

The `upscale_elasticity_*` test failures look unrelated to this PR, though
```
grep Error: dbg/seq/dune-2.3.1/opm-upscaling/Testing/Temporary/LastTest.log 
Error: Filename /data/projects/opm/build/opm/dbg/seq/dune-2.3.1/opm-upscaling/tests/results/upscale_elasticity_mpc_EightCells.txt not found or not readable.
Error: Filename /data/projects/opm/build/opm/dbg/seq/dune-2.3.1/opm-upscaling/tests/results/upscale_elasticity_mortar_EightCells.txt not found or not readable.
```

**Comment by akva2** [comment]
didn't touch those but i want to figure out what's going on in any case (sorry for the delay, got derailed).

can you please do ctest -V

**Comment by akva2** [comment]
anyways, i am out for today so i will get back to this tomorrow.

**Comment by bska** [comment]
> i am out for today so i will get back to this tomorrow.

Okay.  In the meantime I've sent you the `ctest -V` output offline, but the crux of the matter appears to be

```
[...]
14: 	assembling YZ mortar matrix...
14: /home/bska/work/opm/src/opm/opm-upscaling/tests/runtest.sh: line 15: 24813 Segmentation fault      $BINPATH/$EXE_NAME $TEST_ARGS
```

However, that's not particularly helpful so I've `set -x`'ed the `runtest.sh` script, determined that the actual command that gets run is
```
/data/projects/opm/build/opm/dbg/seq/dune-2.3.1/opm-upscaling/bin/upscale_elasticity output=/data/projects/opm/build/opm/dbg/seq/dune-2.3.1/opm-upscaling/tests/results/upscale_elasticity_mortar_EightCells.txt gridfilename=/data/projects/opm/build/opm/dbg/seq/dune-2.3.1/opm-upscaling/tests/input_data/grids/EightCells.grdecl method=mortar
```
and upon running `upscale_elasticity` in GDB get the following backtrace
```
(gdb) bt
#0  0x00007ffff603b2f0 in __gnu_debug::_Safe_sequence_base::_M_detach_all() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#1  0x0000000000cb3d76 in __gnu_debug::_Safe_sequence_base::~_Safe_sequence_base (this=0x7fffffffbc60, __in_chrg=<optimised out>) at /usr/include/c++/4.8/debug/safe_base.h:198
#2  0x0000000000de2558 in __gnu_debug::_Safe_sequence<std::__debug::vector<Dune::QuadraturePoint<double, 1>, std::allocator<Dune::QuadraturePoint<double, 1> > > >::~_Safe_sequence (this=0x7fffffffbc60, __in_chrg=<optimised out>) at /usr/include/c++/4.8/debug/safe_sequence.h:111
#3  0x0000000000de25c0 in std::__debug::vector<Dune::QuadraturePoint<double, 1>, std::allocator<Dune::QuadraturePoint<double, 1> > >::~vector (this=0x7fffffffbc48, __in_chrg=<optimised out>) at /usr/include/c++/4.8/debug/vector:144
#4  0x0000000000de24e9 in Dune::QuadratureRule<double, 1>::~QuadratureRule (this=0x7fffffffbc40, __in_chrg=<optimised out>) at /home/bska/work/opm/inst/dune/2.3.1/dbg/seq/include/dune/geometry/quadraturerules.hh:117
#5  0x0000000000df13db in Dune::GaussQuadratureRule1D<double>::~GaussQuadratureRule1D (this=0x7fffffffbc40, __in_chrg=<optimised out>) at /home/bska/work/opm/inst/dune/2.3.1/dbg/seq/include/dune/geometry/quadraturerules.hh:219
#6  0x0000000000de20c0 in Dune::QuadratureRuleFactory<double, 1>::rule (t=..., p=2, qt=Dune::QuadratureType::Gauss) at /home/bska/work/opm/inst/dune/2.3.1/dbg/seq/include/dune/geometry/quadraturerules.hh:671
#7  0x0000000000dcf175 in Dune::QuadratureRules<double, 1>::_rule (this=0x15a2668 <Dune::QuadratureRules<double, 1>::instance()::instance>, t=..., p=2, qt=Dune::QuadratureType::Gauss) at /home/bska/work/opm/inst/dune/2.3.1/dbg/seq/include/dune/geometry/quadraturerules.hh:158
#8  0x0000000000dbcb3a in Dune::QuadratureRules<double, 1>::rule (t=..., p=2, qt=Dune::QuadratureType::Gauss) at /home/bska/work/opm/inst/dune/2.3.1/dbg/seq/include/dune/geometry/quadraturerules.hh:175
#9  0x0000000000da8b46 in Dune::TensorProductQuadratureRule<double, 2>::TensorProductQuadratureRule (this=0x7fffffffbfa0, topologyId=3, order=2, qt=Dune::QuadratureType::Gauss) at /home/bska/work/opm/inst/dune/2.3.1/dbg/seq/include/dune/geometry/quadraturerules/tensorproductquadrature.hh:36
#10 0x0000000000d9021f in Dune::QuadratureRuleFactory<double, 2>::rule (t=..., p=2, qt=Dune::QuadratureType::Gauss) at /home/bska/work/opm/inst/dune/2.3.1/dbg/seq/include/dune/geometry/quadraturerules.hh:697
#11 0x0000000000d78879 in Dune::QuadratureRules<double, 2>::_rule (this=0x15a2600 <Dune::QuadratureRules<double, 2>::instance()::instance>, t=..., p=2, qt=Dune::QuadratureType::Gauss) at /home/bska/work/opm/inst/dune/2.3.1/dbg/seq/include/dune/geometry/quadraturerules.hh:158
#12 0x0000000000d2f4d1 in Dune::QuadratureRules<double, 2>::rule (t=..., p=2, qt=Dune::QuadratureType::Gauss) at /home/bska/work/opm/inst/dune/2.3.1/dbg/seq/include/dune/geometry/quadraturerules.hh:175
#13 0x0000000000d6e440 in Opm::Elasticity::ElasticityUpscale<Dune::CpGrid, Opm::Elasticity::AMG1<Dune::SeqSSOR<Dune::BCRSMatrix<Dune::FieldMatrix<double, 1, 1>, std::allocator<Dune::FieldMatrix<double, 1, 1> > >, Dune::BlockVector<Dune::FieldVector<double, 1>, std::allocator<Dune::FieldVector<double, 1> > >, Dune::BlockVector<Dune::FieldVector<double, 1>, std::allocator<Dune::FieldVector<double, 1> > >, 1> > >::assembleBBlockMortar (this=0x7fffffffd0a0, b1=..., interface=..., dir=0, n1=1, n2=2, colofs=0, alpha=1) at /home/bska/work/opm/src/opm/opm-upscaling/opm/elasticity/elasticity_upscale_impl.hpp:301
#14 0x0000000000d22191 in Opm::Elasticity::ElasticityUpscale<Dune::CpGrid, Opm::Elasticity::AMG1<Dune::SeqSSOR<Dune::BCRSMatrix<Dune::FieldMatrix<double, 1, 1>, std::allocator<Dune::FieldMatrix<double, 1, 1> > >, Dune::BlockVector<Dune::FieldVector<double, 1>, std::allocator<Dune::FieldVector<double, 1> > >, Dune::BlockVector<Dune::FieldVector<double, 1>, std::allocator<Dune::FieldVector<double, 1> > >, 1> > >::periodicBCsMortar (this=0x7fffffffd0a0, min=0x7fffffffdce8, max=0x7fffffffdd00, n1=2, n2=2, p1=2, p2=2) at /home/bska/work/opm/src/opm/opm-upscaling/opm/elasticity/elasticity_upscale_impl.hpp:880
#15 0x0000000000ce3456 in run<Dune::CpGrid, Opm::Elasticity::AMG1<Dune::SeqSSOR<Dune::BCRSMatrix<Dune::FieldMatrix<double, 1, 1>, std::allocator<Dune::FieldMatrix<double, 1, 1> > >, Dune::BlockVector<Dune::FieldVector<double, 1>, std::allocator<Dune::FieldVector<double, 1> > >, Dune::BlockVector<Dune::FieldVector<double, 1>, std::allocator<Dune::FieldVector<double, 1> > >, 1> > > (p=...) at /home/bska/work/opm/src/opm/opm-upscaling/examples/upscale_elasticity.cpp:345
#16 0x0000000000cc466b in runAMG<Opm::Elasticity::AMG1> (p=...) at /home/bska/work/opm/src/opm/opm-upscaling/examples/upscale_elasticity.cpp:455
#17 0x0000000000caedd8 in main (argc=4, argv=0x7fffffffde98) at /home/bska/work/opm/src/opm/opm-upscaling/examples/upscale_elasticity.cpp:487
```

Just from a cursory glance this **appears** to be a Dune error and I can't reproduce it if I turn off the checked iterator support, so it may not be critical.

**Comment by akva2** [comment]
i cannot reproduce the issue with or without iterator bound checks on my machine, and no out-of-bounds is flagged by valgrind. this is definitely some funky local issue, bug or particular compiler option related. i think this is one of the things where you just have to move on.. please merge.

**Comment by atgeirr** [comment]
I'll try to run this on my system, and report. Please hold off merging until after that.

**Comment by atgeirr** [comment]
All 14 tests succeed in debug (but not iterator checking) and release on my system. Will merge.

**Comment by akva2** [comment]
thanks.

**Pull request merged**
