### PR TITLE
Import opm-porsol

### PR DESCRIPTION
**Pull request by akva2**
This imports the contents of opm-porsol into opm-upscaling. It retains as much history as possible, but history which required --follow in the original repos will not carry over. This is a limitation of git filter-branch; in particular --prune-empty will remove these commits. The alternative is carrying a lot of empty commits, those which only changed buildsystem things in opm-porsol. I deemed it the better choice as most of the history lost is of the type 'import code from somewhere else'.

This has been requested by @alfbr. The next step in the process is to trim some fat from the porsol code, but I would like to get this in first.

Companion PR in opm-common: https://github.com/OPM/opm-common/pull/91
Companion PR in opm-porsol: https://github.com/OPM/opm-porsol/pull/145

### CODE REVIEW

**Comment by akva2** [comment]
the last two commits contains  the "new content".

**Comment by bska** [comment]
> This imports the contents of opm-porsol into opm-upscaling

Any chance the import could omit the `attic` directory?

**Comment by akva2** [comment]
sure, i can redo without that (it's easy enough no worries).

**Comment by bska** [comment]
>> Any chance the import could omit the attic directory?
>
> sure, i can redo without that

Thanks.  I don't think we need to continue to distribute stuff that no-one's looked at for several years.  If we want it we can get it from the original opm-porsol repo.  I will at least preserve a public copy of opm-porsol on my GitHub account even if the official OPM bits are decommissioned and removed.

**Comment by akva2** [comment]
requested premature spring cleaning done.

@atgeirr, it's a lovely github bug when somebody @ quoted you in a commit message and then a rebased branch with the commit is pushed. (if you wonder why you get those ancient emails again..)

**Comment by atgeirr** [comment]
> if you wonder why you get those ancient emails again

I did at first, but understood it when I saw the PR. It's comforting to know that github likes me.

**Comment by bska** [comment]
> requested premature spring cleaning done.

Asking that we not drag in 200 kB of obsolete data is not premature.

**Comment by akva2** [comment]
hehe. nope, but it's not spring yet :)

**Pull request merged**
