### PR TITLE
remove the configure wrapper script

### PR DESCRIPTION
**Pull request by andlaus**
this used to provide autotools compatibility, but it has not been working for a while. Thus it is IMO better to remove it in order not to mislead people.

### CODE REVIEW

**Comment by akva2** [comment]
finally.

**Comment by andlaus** [comment]
can you have a look at OPM/opm-common#287 because this is very annoying for people who are not interested in flow...

**Comment by akva2** [comment]
i don't see anything that wasn't user error in there. the _ROOT support has been removed as it's long outdated in cmake itself. you use _DIR if you want to use out of a build dir,  or a prefix path for an installation.

**Comment by andlaus** [comment]
sure, but regardless of whether that's correct or not the cmake module should either fail or succeed, not report success first, then failure and then break the downstream build system?

**Comment by akva2** [comment]
uhm, what? did you link something other than you think you did or something?

**Comment by andlaus** [comment]
oops, sorry. yes, wrong issue. I was talking about OPM/opm-common#289

**Comment by akva2** [comment]
right. you mentioned the naughty things in there, i cannot touch it.

**Comment by andlaus** [comment]
that's kind of unfortunate. The quick "fix" is to mark opm-core as REQUIRED for ewoms. (it is not, though.)

**Pull request merged**
