### PR TITLE
Fix benchmark build

### PR DESCRIPTION
**Pull request by akva2**
Fix build of benchmark after parser changes.
Enable build of benchmark on jenkins

@alfbr

### CODE REVIEW

**Comment by atgeirr** [comment]
jenkins build this please

**Comment by akva2** [comment]
can we get this off my list please?

**Comment by alfbr** [comment]
From my end this is good to go. @atgeirr , do you want to review?

**Comment by atgeirr** [comment]
Looks fine to me, was only waiting for check before merging.

**Pull request merged**
