### PR TITLE
add missing initializer

### PR DESCRIPTION
**Pull request by akva2**

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this please

**Comment by bska** [comment]
Looks good.  Thanks!  I'll merge into master.

**Comment by blattms** [comment]
should this make into the release?

**Comment by akva2** [comment]
it's not really crucial, as there is no change in code, just kills a (harmless) warning. but it would not harm either. sorry for forgetting to tag the PRs yesterday, i planned to ping them today.

**Pull request merged**
