### PR TITLE
Chase ParseMode -> ParseContext Renaming in Examples

### PR DESCRIPTION
**Pull request by bska**
Example programs forgotten in #171.

### CODE REVIEW

**Comment by qilicun** [comment]
Thansk! I remembered that I have add these files, probably forgotten to commit.

**Comment by qilicun** [comment]
Please change this alos ``benchmarks/upscale_relperm_benchmark.cpp``

**Comment by bska** [comment]
> `benchmarks/upscale_relperm_benchmark.cpp`

Thanks for pointing that out.  Fixed in e6c8d68.

**Comment by qilicun** [comment]
Could I touch the green button?

**Comment by bska** [comment]
I'll self-merge this to restore the build.

**Pull request merged**
