### PR TITLE
Use specific headers S.hpp and P.hpp

### PR DESCRIPTION
**Pull request by joakim-hove**
Preparation for removing the large keyword header.

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by bska** [comment]
Just out of curiosity, why are we removing `ParserKeywords.hpp`?  I absolutely get splitting the `.cpp` file to expose more (compiler) parallelism, but the header is essentially just
```C++
#include A
// ...
#include Z
```
and if you actually need to do that it is very convenient to have it&mdash;especially if at some point we further subdivide the generated keywords into `A0.hpp`..`Z9.hpp`

On the other hand, I also get that "include what you use" implies that `ParserKeywords.hpp` should be rare outside of the generator itself.

**Comment by joakim-hove** [comment]
> On the other hand, I also get that "include what you use" implies that ParserKeywords.hpp should be rare outside of the generator itself.

It is not an important point - just a small nudge in the direction of "include what you use"; I'd be happy to reinstate if people think it should be around. That said this #include statement was the *only* one in all of opm.

**Comment by bska** [comment]
> > On the other hand, I also get that "include what you use" implies that `ParserKeywords.hpp` should be rare outside of the generator itself.
> 
> [...] I'd be happy to reinstate if people think it should be around.

Okay, let's decouple this instance and reevaluate if the need arises.

**Pull request merged**
