### PR TITLE
remove stale static benchmark target

### PR DESCRIPTION
**Pull request by akva2**
unmaintained for 10 years with no complainers. let's send this to the eternal fields

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this please

**Comment by alfbr** [comment]
It is a benchmark, so it is basically intended to not change. It has been used to monitor the numerical performance of the upscaling. Is there an incurred maintenance burden?

**Comment by akva2** [comment]
this is not removing the benchmark. 

it's removing some old stuff i added 10 years ago to build a fully static benchmark. i doubt current code builds with the dune 2.3 these targets attempts to build for instance..

**Comment by alfbr** [comment]
Ah, then I misunderstood. By all means, go ahead.

**Pull request merged**
