### PR TITLE
remove the attic

### PR DESCRIPTION
**Pull request by andlaus**
in the spirit of #228 and #227, this removes more old cruft. this time it is even guaranteed that noone uses it because it does not even compile (probably).

### CODE REVIEW

**Comment by akva2** [comment]
indeed, this has not built in years. @atgeirr your button.

**Comment by atgeirr** [comment]
The cpp files should be deleted. However two of the text files contain historical results and timings for the upscaling code, going back to 2006, which I would like to keep somehow. I'd therefore like to keep them alive somehow (and that means in the cloud somewhere permanent-ish, not necessarily github though). I'd appreciate any suggestions for alternative storage spots. Perhaps even clean them up, promote them to PERFORMANCE.md and put them in the root dir?

Or just skip them for now. (This does not in any way hinder or help the opm-core removal so there is no hurry.)

**Comment by andlaus** [comment]
why isn't it sufficient to have these text files in the git history? I bet that nobody looked at them for the last three years (that's when the `attic` directory was last touched). I think we should thus take a similar approach here as when it comes to throwing away old physical stuff: If nobody used something for long enough and it was even forgotten to exist, it should IMO bite the dust despite its nostalgic value.

anyway, once the fabled `opm-legacy` module exists, these files could be resurected there if anyone bothers. IMO they don't belong to modules with productive code, though.

**Comment by atgeirr** [comment]
> I bet that nobody looked at them for the last three years

I looked at them about a year ago... and of course again today!

I disagree with you: we don't throw things away just because it is old, as long as it does not interfere at all with other things.

**Comment by andlaus** [comment]
My point was not mainly that these files are old, but I assert that they are basically *useless* (maybe except for nostalgic value). Anyway, I re-added them and pushed an update.

**Pull request merged**
