### PR TITLE
Fix build after opm material change

### PR DESCRIPTION
**Pull request by akva2**
@andlaus please confirm and merge if correct.

### CODE REVIEW

**Comment by atgeirr** [comment]
I that is all it takes to fix I am relieved!

**Comment by bska** [comment]
jenkins build this please

**Comment by akva2** [comment]
it built and tests passed fine locally (if you don't want to wait through the queue).

**Comment by andlaus** [comment]
ops, mea culpa! The change is correct. (I was not aware that opm-upscaling used opm-material.)

**Pull request merged**
