### PR TITLE
fixed/added: make sure wave speed calculation is tested

### PR DESCRIPTION
**Pull request by akva2**
i was looking into the dune future on request from @blattms when i noticed that the reading of the RHO keyword was no longer supported after the switch to opm-parser. This resulted in https://github.com/OPM/opm-parser/pull/1118

here is the test update to make sure this doesn't happen again.

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this please

**Comment by akva2** [comment]
now with more grdecl update.

**Comment by akva2** [comment]
jenkins build this please

**Comment by akva2** [comment]
just to follow procedure: quick review @atgeirr @bska

**Comment by atgeirr** [comment]
Looks fine and all green, so in it goes!

**Pull request merged**
