### PR TITLE
Make Dune 2.4 mandatory

### PR DESCRIPTION
**Pull request by andlaus**
this PR includes #219 because these two would otherwise clash.

### CODE REVIEW

**Comment by atgeirr** [comment]
jenkins build this opm-common=261 please

**Comment by atgeirr** [comment]
I guess this will not work, as Jenkins is on 2.3 last I heard?

**Comment by andlaus** [comment]
> I guess this will not work, as Jenkins is on 2.3 last I heard?

that was before your vacation, right now it is on 2.4.1 ;) I would gladly provide you with a link to @akva2's message on the OPM mailing list from July 10, but the mailing list infrastructure seems to be partially broken since a few weeks, so archiving does not work.

**Comment by atgeirr** [comment]
As the other "require 2.4" PRs have been merged now this should be, too?

@andlaus, please resolve conflicts here

**Comment by akva2** [comment]
my version was more thorough, this can be closed.

**Comment by atgeirr** [comment]
Ah, I did not recall this was included in the other PR, sorry for the noise! (And now I made even more...)

**Pull request closed without merging**
