### PR TITLE
added: migrate medium benchmark from opm-benchmarks

### PR DESCRIPTION
**Pull request by akva2**
- migrate medium data set from opm-benchmarks
- add a 'benchmark' target to build the benchmark in your build tree
- add a 'benchmark-static' target to build a static benchmark binary

just say so if you prefer multiple commits, i grouped since it's all one functional change.

### CODE REVIEW

**Comment by atgeirr** [comment]
This did not cause compilation of the usual parts to fail, but `make benchmarks` failed, and I think for the same reason that it fails in opm-benchmarks for me currently (so no change for me unfortunately). I get several errors of this kind:
```
/Users/atgeirr/opm-build-release/opm-upscaling-build/benchmarks/input/benchmark20_upscaled_relperm.out.gz.hex:112:52: error: invalid suffix 'x' on integer constant
```
The line (112) in question is the last in the file, and looks quite wrong:
```
0xfd,0x0b,0xdd,0x48,0xe7,0x90,0x84,0x0f,0x00,0x00,0x,
```

**Comment by akva2** [comment]
yeah, i suspected as much. it's a shell script using sed and linux sed is highly non-portable to osx.

**Comment by bska** [comment]
> it's a shell script using sed and linux sed is highly non-portable to osx.

Normally I'd agree, but there are no non-portable constructs in the sed script.  It is Posix only.  I rather suspect it's the output from `od` (or `gzip`) that's ever so slightly different on OS X compared to Linux.

**Comment by atgeirr** [comment]
> linux sed is highly non-portable

I have seen that happen quite a lot over the years, with sed or other similar tools. Are there alternative tools that might be more portable? Awk, even perl?

Anyway, even without fixing that, the current PR did not ruin anything so it is ok from that perspective.

**Comment by akva2** [comment]
could also be. can we see 'od -v -t x1' output for some random file atgeirr ?

**Comment by atgeirr** [comment]
OK:
```
atgeirr@arwen:~/opm-build-release/opm-upscaling-build$ od -v -t x1 dune.module 
0000000    23  23  23  23  23  23  23  23  23  23  23  23  23  23  23  23
0000020    23  23  23  23  23  23  23  23  23  23  23  23  23  23  23  23
0000040    0a  23  20  44  75  6e  65  20  6d  6f  64  75  6c  65  20  69
0000060    6e  66  6f  72  6d  61  74  69  6f  6e  20  66  69  6c  65  20
0000100    23  0a  23  23  23  23  23  23  23  23  23  23  23  23  23  23
0000120    23  23  23  23  23  23  23  23  23  23  23  23  23  23  23  23
0000140    23  23  0a  0a  23  4e  61  6d  65  20  6f  66  20  74  68  65
0000160    20  6d  6f  64  75  6c  65  0a  4d  6f  64  75  6c  65  3a  20
0000200    6f  70  6d  2d  75  70  73  63  61  6c  69  6e  67  0a  44  65
0000220    73  63  72  69  70  74  69  6f  6e  3a  20  44  55  4e  45  20
0000240    6d  6f  64  75  6c  65  20  63  6f  6e  74  61  69  6e  69  6e
0000260    67  20  73  69  6e  67  6c  65  2d  70  68  61  73  65  20  61
0000300    6e  64  20  73  74  65  61  64  79  2d  73  74  61  74  65  20
0000320    75  70  73  63  61  6c  69  6e  67  20  6d  65  74  68  6f  64
0000340    73  0a  56  65  72  73  69  6f  6e  3a  20  31  2e  30  0a  4c
0000360    61  62  65  6c  3a  20  32  30  31  33  2e  31  30  0a  4d  61
0000400    69  6e  74  61  69  6e  65  72  3a  20  61  72  6e  65  2e  6d
0000420    6f  72  74  65  6e  2e  6b  76  61  72  76  69  6e  67  40  73
0000440    69  6e  74  65  66  2e  6e  6f  0a  23  64  65  70  65  6e  64
0000460    69  6e  67  20  6f  6e  20  0a  44  65  70  65  6e  64  73  3a
0000500    20  64  75  6e  65  2d  63  6f  6d  6d  6f  6e  20  64  75  6e
0000520    65  2d  67  72  69  64  20  64  75  6e  65  2d  69  73  74  6c
0000540    20  64  75  6e  65  2d  63  6f  72  6e  65  72  70  6f  69  6e
0000560    74  20  6f  70  6d  2d  70  6f  72  73  6f  6c  0a            
0000575
```

**Comment by bska** [comment]
>> can we see 'od -v -t x1' output for some random file atgeirr ?
>
> OK:
>
``` 
atgeirr@arwen:~/opm-build-release/opm-upscaling-build$ od -v -t x1 dune.module 
0000000    23  23  23  23  23  23  23  23  23  23  23  23  23  23  23  23
```

That looks fair enough.  Just to try to eliminate components, could you run the following commands in sequence (in an opm-upscaling based on #152)?
```sh
inputfile=benchmarks/input/benchmark20_grid.grdecl
cat "${inputfile}" | wc
cat "${inputfile}" | gzip -9 | wc
cat "${inputfile}" | gzip -9 | od -v -t x1 | wc
```

**Comment by akva2** [comment]
it could be github, but from what i got copying the block quote it seems osx od pads with spaces, linux does not (next-to-last line).

**Comment by akva2** [comment]
one approach that i think should be portable. please try @atgeirr

**Comment by atgeirr** [comment]
```
od: illegal option -- w
usage: od [-aBbcDdeFfHhIiLlOosvXx] [-A base] [-j skip] [-N length] [-t type]
          [[+]offset[.][Bb]] [file ...]
```

**Comment by akva2** [comment]
hmm, this one then. i *think* this one should stick within the confinements of bsdutils unless my awk is gnu'y as well.

**Comment by akva2** [comment]
some cleanup commits added. the last one gives that cosy warm deja vu feeling only cut and paste coding can bring forth (to be adressed later).

**Comment by akva2** [comment]
@atgeirr would be great if you could test the new version.

**Comment by atgeirr** [comment]
Now I successfully both built and ran the benchmark. Thanks!

**Comment by bska** [comment]
> Now I successfully both built and ran the benchmark. Thanks!

Cool.  I still don't understand why the sed script fails, but I'm not going to quibble over it.  I'll merge this (and the prerequisite OPM/opm-cmake#24) into master.

**Pull request merged**
