### PR TITLE
Force opm-grid to pinch.

### PR DESCRIPTION
**Pull request by blattms**
downstream of OPM/opm-grid#539

### CODE REVIEW

**Comment by alfbr** [comment]
My preference is to always have PINCH activated for the upscaling, since none of the softwares used for input set PINCH in the grdecl file (meaning then users will need to know about it, and manually set PINCH in all grids before upscaling). Not sure how easy that is to do in the current upscaling code though.

**Comment by bska** [comment]
> My preference is to always have PINCH activated for the upscaling, since none of the softwares used for input set PINCH in the grdecl file

Yes please!

**Comment by blattms** [comment]
Ok. we now pass true for `pinchActive` to `CpGrid` whenever we call `CpGrid::processEclipseFormat`

**Comment by alfbr** [comment]
Thank you! Now, crossing fingers for all tests to pass without changing reference solutions :-)

**Comment by akva2** [comment]
try undrafting.

**Review by bska — APPROVED** [review]
Looks good to me.  I'll merge once the upstream PR is in the build queue.

**Comment by bska** [comment]
> I'll merge once the upstream PR is in the build queue.

Post-commit build is running.  I'll merge this now.

**Pull request merged**
