### PR TITLE
Move man pages to doc and install them.

### PR DESCRIPTION
**Pull request by blattms**
The directory doc already exists and there does not seem a need to introduce docs as an additional source of documentation.

With this change the doc layout is similar to opm-common and opm-simulators.

### CODE REVIEW

**Comment by blattms** [comment]
jenkins build this please

**Comment by blattms** [comment]
Also fixed the formatting and other stuff.

**Comment by blattms** [comment]
jenkins build this please

**Comment by blattms** [comment]
jenkins build this please

**Comment by blattms** [comment]
@bska Fixed. @akva2 probably needs to do something for the manpages in the packages.

**Comment by bska** [comment]
jenkins build this please

**Review by bska — APPROVED** [review]
Thanks for the updates.  I'll merge this into master now and then defer to @akva2 on how to deal with the packaging issues.

**Pull request merged**
