### PR TITLE
Remove sstream use in exception handling

### PR DESCRIPTION
**Pull request by akva2**
Preparatory work for removing sstream usage in OPM_THROW.

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this please

**Comment by akva2** [comment]
just to give some ballpark numbers. with this PR and the various stream cleanups in downstreams:

before: 
- istream includes: 723
- ostream includes: 1295

after:
-istream includes: 673
- ostream includes: 1189

on my machine parsing istream takes approximately 0.3 sec, and parsing ostream takes approximately 0.25 sec.

thus this effort saves (1295-1189)*0.25 + (723-673)*0.3 = 41 secs

**Comment by bska** [comment]
jenkins build this please

**Review by bska — APPROVED** [review]
Thanks.  I'll merge into master.  There are some weird whitespace changes here, but if I recall correctly there are also some files in this module that use tabs for indentation.  We can fix those in one fell swoop later.

**Pull request merged**
