### PR TITLE
Added ParseMode argument

### PR DESCRIPTION
**Pull request by joakim-hove**
Followup to: https://github.com/OPM/opm-parser/pull/527

### CODE REVIEW

**Comment by akva2** [comment]
thanks.

**Comment by joakim-hove** [comment]
Ehhh - that was maybe a bit fast; the upstream PR has not been merged yet.

**Comment by notspiff** [comment]
Grm my bad. On vacation, description said follow up. Shouldnt skip steps..

**Comment by joakim-hove** [comment]
Should I force push a rewind?

**Comment by akva2** [comment]
No it will likely cause issues on builders. Either we wait or we revert.

-------- Opprinnelig melding --------
Fra: Joakim Hove <notifications@github.com>
Dato: 27.07.2015 17.47 (GMT+01:00)
Til: OPM/opm-upscaling <opm-upscaling@noreply.github.com>
Ko: Arne Morten Kvarving <Arne.Morten.Kvarving@sintef.no>
Emne: Re: [opm-upscaling] Added ParseMode argument (#154)


Should I force push a rewind?

**Comment by joakim-hove** [comment]
OK; it is up to you - but the plan was actually to hold back the upstream PR for a couple of days - to allow some time for comments. These are quiet times - my suggestion is to wait?

**Comment by akva2** [comment]
Agreed. We can handle a few days. Not much going on.

-------- Opprinnelig melding --------
Fra: Joakim Hove <notifications@github.com>
Dato: 27.07.2015 18.02 (GMT+01:00)
Til: OPM/opm-upscaling <opm-upscaling@noreply.github.com>
Ko: Arne Morten Kvarving <Arne.Morten.Kvarving@sintef.no>
Emne: Re: [opm-upscaling] Added ParseMode argument (#154)


OK; it is up to you - but the plan was actually to hold back the upstream PR for a couple of days - to allow some time for comments. These are quiet times - my suggestion is to wait?

**Pull request merged**
