### PR TITLE
Remove obsolete application

### PR DESCRIPTION
**Pull request by alfbr**
It seems upscale_singlephase was made obosolete by upscale_perm years ago. Please shout out if you want to keep it alive.

### CODE REVIEW

**Comment by alfbr** [comment]
jenkins build this please

**Comment by alfbr** [comment]
jenkins build this please

**Comment by alfbr** [comment]
@atgeirr maybe you can assess if this application should be kept?

**Comment by alfbr** [comment]
But upscale_perm can serve the same purpose for you? Yes, the program is minimal, but documentation is missing to the point that I do not understand how to run it at all. Right now we need to make man pages for all apps as a preparation for Debian packages, so there is a cost also for minimal apps.

**Comment by atgeirr** [comment]
> But upscale_perm can serve the same purpose for you? Yes, the program is minimal, but documentation is missing to the point that I do not understand how to run it at all. Right now we need to make man pages for all apps as a preparation for Debian packages, so there is a cost also for minimal apps.

I see that, and it is ok to delete.

**Pull request merged**
