### PR TITLE
Commit: Several tests for the relperm upscaling 

### PR DESCRIPTION
**Pull request by lkerrand**
Several tests for the relperm upscaling have been implemented with new grid, stonefiles and the reference solutions.

The reference solutions added are run with the `EightCells` grid or the `27cellsAniso` grid, the two other reference solutions run with the `16cells` grid and the gravity option are elements to show a bug that will be reported.

For the different options the tests are:

 * `-points`: default 30 , test 20
 * `-BC`: default fixed (`f`), test periodic (`p`)
 * `-surfaceTension`: default 11Dyn/cm, test 45 Dyn/cm
 * `-stonefiles`: use of two stonefile for Rock type 1 and rock type 2 (RT1&2)
 * `-interpolate`: no default, test 100 points
 * `-critRelpermThresh`: default `1e-6` for `Krw_min`, test with `stonefileRT1_Thresh` needs to use a crit. of 0.00011

Viscosity test have not been implemented as it did not show any noticeable modifications of the results.
It has also been necessary to modify the `CMakeLists_files.cmake` file and the `TestUpscalingBinaries.cmake` file.

### CODE REVIEW

**Comment by akva2** [comment]
this does not even configure. you are passing only two arguments to some of the add_test_upscale_relperm calls.

**Comment by lkerrand** [comment]
Sorry for the hasty pull request, I still need some time to finish the compiling. 
I'll come back

**Comment by akva2** [comment]
right. in the future please state that this is WIP so i won't hop on it too early :)
also may i request that you don't  ask to pull your master, use a feature branch. lowers the chance of unrelated things getting mixed up, in particular if it takes a while for a pull request to be processed.

**Comment by lkerrand** [comment]
Hi,
The last commit use files that have been properly compiled and the added test runs properly, it should be ok for reviewing (I hope!)

**Comment by akva2** [comment]
why are you removing a test ?

**Comment by akva2** [comment]
and i suspect there should be new files here ? lots of new files referenced but no new files added.

**Comment by lkerrand** [comment]
Ok, there is a bug in my commit, I shall fix it right now

**Comment by lkerrand** [comment]
Ok, I added the missing files. the file which appears to be deleted has been renamed only

**Comment by akva2** [comment]
uhm, try again. we do not want all those generated files added.

**Comment by bska** [comment]
> Ok, I added the missing files

And a lot of other stuff.  Did you really mean to add the entire `build` directory?

**Comment by lkerrand** [comment]
I have not been informed concerning the build directory if it would be better not to include it: I remove it right away if it is not helpful

**Comment by akva2** [comment]
build/ is the generated buildsystem. everything in there is throw-away, machine specific data.

**Comment by bska** [comment]
> build/ is the generated buildsystem. everything in there is throw-away, machine specific data.

Note, in particular, all the references to `/private/lker/OPM_Compile`.  This path is unlikely to exist on other systems.

**Comment by lkerrand** [comment]
My apologies

**Comment by akva2** [comment]
now please squash it into a reviewable state.

use 
```
git rebase -i HEAD~5
```

in the editor that pops up, keep the first line prefixed with 'pick' and change the other 3 into 's' for squash.

then choose the commit message you want for the combined commits in the editor that pops up.

finally force-push the branch to github;
```
git push -f origin master
```

assuming your github repo is the origin remote. you have to force since the interactive rebase above rewrite history.

**Comment by atgeirr** [comment]
> assuming your github repo is the origin remote.

Please check this first! This is what it looks like to me (you should probably have an http URL instead of ssh as the "upstream".
```
atgeirr@galadriel:~/opm/opm-upscaling$ git remote -v
origin	git@github.com:atgeirr/opm-upscaling.git (fetch)
origin	git@github.com:atgeirr/opm-upscaling.git (push)
upstream	git@github.com:OPM/opm-upscaling.git (fetch)
upstream	git@github.com:OPM/opm-upscaling.git (push)
```

**Comment by lkerrand** [comment]
I only have SSH as the "upstream" : 
:~/OPM_Compile/opm-upscaling:$ git remote -v
origin  git@github.com:lkerrand/opm-upscaling.git (fetch)
origin  git@github.com:lkerrand/opm-upscaling.git (push)
upstream        git@github.com:OPM/opm-upscaling.git (fetch)
upstream        git@github.com:OPM/opm-upscaling.git (push)

**Comment by atgeirr** [comment]
> I only have SSH as the "upstream" :

That means you can accidentally push commits directly into the upstream repo, I suggest you change it to the http URL.

**Comment by lkerrand** [comment]
Ok, thanks

**Comment by akva2** [comment]
still two commits in the branch and the first one touches a non-relevant file (dune.module).

**Comment by lkerrand** [comment]
I am not sure of what happened with the "squash": what appears to be the "Squash commit according to last recommendations" is an old and incorrect commit with unjustified changes of dune.module.
On the contrary the  "Combination of commits" contains the last version of commits, without build and leaving the dune.module unchanged.

**Comment by akva2** [comment]
i don't know what you have done but i suggest

1) drop your commits
 ```
git reset origin/master.
```
this will leave your changes in your working tree, but none of them will be in a commit.
2) add *only* the files you want in the commit through
```
git add <file>
```
3) recreate commit

**Comment by akva2** [comment]
note i mixed up your remote names - you should reset on upstream, not origin.

**Comment by akva2** [comment]
i had a look at the current state. still very much broken, missing files, passing wrong parameters in TestUpscalingBinaries.cmake (it's 'upscaleBothPhaseS' - last S was missing), it does just {option1} instead of ${option1}.

if you want i guess you can just give me the test data, and the (explicit) commands you want executed for each test and i can do the cmake code and git'ery.

**Comment by lkerrand** [comment]
Ok, thank you for the proposition, I sent en e-mail

**Comment by akva2** [comment]
replaced by https://github.com/OPM/opm-upscaling/pull/166

**Pull request closed without merging**
