### PR TITLE
changed: use std::random instead of boost::random

### PR DESCRIPTION
**Pull request by akva2**
less boost, more happy.

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this please

**Comment by akva2** [comment]
jenkins build this please

**Comment by akva2** [comment]
i did both, just tell me which you want.

**Comment by akva2** [comment]
@bska did you forget this?

**Comment by bska** [comment]
jenkins build this please

**Comment by akva2** [comment]
i prefer to squash if you want the lambdas.

**Comment by akva2** [comment]
jenkins build this please

**Comment by bska** [comment]
> I'll launch a final build test and merge if successful.

Build check okay.  I'll merge into master.  Thanks a lot.

**Pull request merged**
